# Add your code below
version: "3.1"

services:
  mongodb:
    container_name: "hyper-mongo"
    image: mongo:6.0.8
    ports:
      - "27027:27017"
    env_file:
      - ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongo-data:/data/db
    networks:
      - hyper-task-manager-network
  hyper-service:
    build: {'context': '.', 'dockerfile': 'Dockerfile'}
    container_name: "hyper-task-manager"
    ports:
      - "8000:8000"
    networks:
      - hyper-task-manager-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_HOST_NAME: "mongodb"
      MONGO_PORT_NUMBER: 27017
    env_file:
      - ".env"
    depends_on:
      - mongodb


volumes:
  mongo-data:

networks:
  hyper-task-manager-network:
